import Head from 'next/head'
import { SpinnerInfinity } from 'spinners-react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Matrix Bank Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
          <div className="main-con">
              <h1>Matrix Bank is under development, please check back later!</h1>
              <SpinnerInfinity
                  size="40%"
                  color='#00264D'
                  secondaryColor="#fff"
              />
          </div>
      </main>
    </>
  )
}
